export type SeedEndpoint = {
  code: string;
  name: string;
  category:
    | "search"
    | "social"
    | "marketplace"
    | "appstore"
    | "darkweb"
    | "domain"
    | "news"
    | "review"
    | "video"
    | "messaging"
    | "ai";
  description: string;
  enabled: boolean;
  frequencyMin: number;
  priority: 1 | 2 | 3;
  health: "healthy" | "degraded" | "down" | "paused";
  latencyMs: number;
  successRate: number;
  hits24h: number;
  costPer1k: number;
  requiresKey: boolean;
  keySet: boolean;
  region?: string;
  concurrency: number;
  tag?: string;
  baseUrl?: string;
};

export const SEED_ENDPOINTS: SeedEndpoint[] = [
  {
    code: "google",
    name: "Google Search API",
    category: "search",
    description: "SERP web, imagens, notícias e shopping.",
    enabled: true,
    frequencyMin: 5,
    priority: 1,
    health: "healthy",
    latencyMs: 320,
    successRate: 99.4,
    hits24h: 18420,
    costPer1k: 3.2,
    requiresKey: true,
    keySet: false,
    region: "BR",
    concurrency: 20,
    tag: "Core",
  },
  {
    code: "bing",
    name: "Bing Web Search",
    category: "search",
    description: "Cobertura complementar em EN e LATAM.",
    enabled: true,
    frequencyMin: 15,
    priority: 2,
    health: "healthy",
    latencyMs: 410,
    successRate: 98.1,
    hits24h: 6240,
    costPer1k: 2.1,
    requiresKey: true,
    keySet: false,
    region: "GLOBAL",
    concurrency: 10,
  },
  {
    code: "duckduckgo",
    name: "DuckDuckGo Scraper",
    category: "search",
    description: "Fallback anônimo sem chave de API.",
    enabled: false,
    frequencyMin: 60,
    priority: 3,
    health: "paused",
    latencyMs: 780,
    successRate: 92.3,
    hits24h: 0,
    costPer1k: 0,
    requiresKey: false,
    keySet: true,
    concurrency: 4,
  },
  {
    code: "yandex",
    name: "Yandex Search",
    category: "search",
    description: "Cobertura CIS e RU.",
    enabled: false,
    frequencyMin: 60,
    priority: 3,
    health: "paused",
    latencyMs: 900,
    successRate: 95,
    hits24h: 0,
    costPer1k: 1.4,
    requiresKey: true,
    keySet: false,
    concurrency: 4,
  },
  {
    code: "instagram",
    name: "Instagram Graph API",
    category: "social",
    description: "Perfis, posts, reels e hashtags.",
    enabled: true,
    frequencyMin: 10,
    priority: 1,
    health: "healthy",
    latencyMs: 540,
    successRate: 97.9,
    hits24h: 9210,
    costPer1k: 0,
    requiresKey: true,
    keySet: false,
    concurrency: 8,
    tag: "OAuth",
  },
  {
    code: "tiktok",
    name: "TikTok Research API",
    category: "social",
    description: "Vídeos, contas suspeitas e trending sounds.",
    enabled: true,
    frequencyMin: 15,
    priority: 1,
    health: "degraded",
    latencyMs: 1200,
    successRate: 88.2,
    hits24h: 4310,
    costPer1k: 0,
    requiresKey: true,
    keySet: false,
    concurrency: 6,
    tag: "Beta",
  },
  {
    code: "facebook",
    name: "Facebook Pages Feed",
    category: "social",
    description: "Fanpages, grupos públicos e Marketplace.",
    enabled: true,
    frequencyMin: 20,
    priority: 2,
    health: "healthy",
    latencyMs: 620,
    successRate: 96.5,
    hits24h: 3120,
    costPer1k: 0,
    requiresKey: true,
    keySet: false,
    concurrency: 6,
  },
  {
    code: "x",
    name: "X (Twitter) API v2",
    category: "social",
    description: "Tweets, listas e menções em tempo real.",
    enabled: true,
    frequencyMin: 5,
    priority: 1,
    health: "healthy",
    latencyMs: 280,
    successRate: 99,
    hits24h: 15200,
    costPer1k: 5.0,
    requiresKey: true,
    keySet: false,
    concurrency: 15,
  },
  {
    code: "linkedin",
    name: "LinkedIn Company API",
    category: "social",
    description: "Perfis corporativos, vagas e conteúdo.",
    enabled: true,
    frequencyMin: 30,
    priority: 2,
    health: "healthy",
    latencyMs: 700,
    successRate: 97.2,
    hits24h: 890,
    costPer1k: 0,
    requiresKey: true,
    keySet: false,
    concurrency: 4,
  },
  {
    code: "threads",
    name: "Threads (Meta)",
    category: "social",
    description: "Publicações públicas via Graph.",
    enabled: false,
    frequencyMin: 30,
    priority: 3,
    health: "paused",
    latencyMs: 600,
    successRate: 95,
    hits24h: 0,
    costPer1k: 0,
    requiresKey: true,
    keySet: false,
    concurrency: 3,
  },
  {
    code: "bluesky",
    name: "Bluesky AT Protocol",
    category: "social",
    description: "Firehose e busca AT Proto.",
    enabled: false,
    frequencyMin: 60,
    priority: 3,
    health: "paused",
    latencyMs: 500,
    successRate: 96,
    hits24h: 0,
    costPer1k: 0,
    requiresKey: false,
    keySet: true,
    concurrency: 2,
  },
  {
    code: "mercadolivre",
    name: "Mercado Livre API",
    category: "marketplace",
    description: "Listagens, vendedores e anúncios patrocinados.",
    enabled: true,
    frequencyMin: 15,
    priority: 1,
    health: "healthy",
    latencyMs: 420,
    successRate: 98.7,
    hits24h: 5810,
    costPer1k: 0,
    requiresKey: true,
    keySet: false,
    region: "BR",
    concurrency: 8,
    tag: "Core",
  },
  {
    code: "shopee",
    name: "Shopee Open API",
    category: "marketplace",
    description: "Produtos, lojas e ranking de busca.",
    enabled: true,
    frequencyMin: 30,
    priority: 1,
    health: "healthy",
    latencyMs: 680,
    successRate: 96.1,
    hits24h: 3220,
    costPer1k: 0,
    requiresKey: true,
    keySet: false,
    region: "BR",
    concurrency: 6,
  },
  {
    code: "amazon",
    name: "Amazon SP-API",
    category: "marketplace",
    description: "ASINs, sellers e Buy Box.",
    enabled: true,
    frequencyMin: 30,
    priority: 2,
    health: "degraded",
    latencyMs: 1400,
    successRate: 90.4,
    hits24h: 1810,
    costPer1k: 0,
    requiresKey: true,
    keySet: false,
    concurrency: 4,
  },
  {
    code: "magalu",
    name: "Magazine Luiza Scraper",
    category: "marketplace",
    description: "Produtos e lojistas parceiros.",
    enabled: true,
    frequencyMin: 60,
    priority: 3,
    health: "healthy",
    latencyMs: 900,
    successRate: 94,
    hits24h: 620,
    costPer1k: 0.8,
    requiresKey: false,
    keySet: true,
    region: "BR",
    concurrency: 3,
  },
  {
    code: "aliexpress",
    name: "AliExpress Affiliate",
    category: "marketplace",
    description: "Cross-border LATAM e importação irregular.",
    enabled: true,
    frequencyMin: 60,
    priority: 2,
    health: "healthy",
    latencyMs: 720,
    successRate: 95.2,
    hits24h: 1140,
    costPer1k: 0,
    requiresKey: true,
    keySet: false,
    concurrency: 4,
  },
  {
    code: "olx",
    name: "OLX Scraper",
    category: "marketplace",
    description: "Anúncios classificados.",
    enabled: false,
    frequencyMin: 60,
    priority: 3,
    health: "paused",
    latencyMs: 1000,
    successRate: 91,
    hits24h: 0,
    costPer1k: 0.6,
    requiresKey: false,
    keySet: true,
    region: "BR",
    concurrency: 2,
  },
  {
    code: "gplay",
    name: "Google Play Scraper",
    category: "appstore",
    description: "Apps clones, permissões e reviews.",
    enabled: true,
    frequencyMin: 60,
    priority: 1,
    health: "healthy",
    latencyMs: 550,
    successRate: 97.8,
    hits24h: 210,
    costPer1k: 0,
    requiresKey: false,
    keySet: true,
    concurrency: 3,
  },
  {
    code: "appstore",
    name: "Apple App Store RSS",
    category: "appstore",
    description: "Apps e reviews via iTunes RSS.",
    enabled: true,
    frequencyMin: 60,
    priority: 1,
    health: "healthy",
    latencyMs: 420,
    successRate: 98.9,
    hits24h: 180,
    costPer1k: 0,
    requiresKey: false,
    keySet: true,
    concurrency: 3,
  },
  {
    code: "apkpure",
    name: "APKPure Mirror Watch",
    category: "appstore",
    description: "Detecta APKs reempacotados.",
    enabled: false,
    frequencyMin: 240,
    priority: 3,
    health: "paused",
    latencyMs: 1200,
    successRate: 88,
    hits24h: 0,
    costPer1k: 0,
    requiresKey: false,
    keySet: true,
    concurrency: 1,
  },
  {
    code: "torch",
    name: "Torch (Tor)",
    category: "darkweb",
    description: "Indexação de .onion.",
    enabled: true,
    frequencyMin: 60,
    priority: 1,
    health: "healthy",
    latencyMs: 2400,
    successRate: 84.5,
    hits24h: 120,
    costPer1k: 0,
    requiresKey: false,
    keySet: true,
    concurrency: 2,
    tag: "Tor",
  },
  {
    code: "ahmia",
    name: "Ahmia .onion Search",
    category: "darkweb",
    description: "Fontes hidden services.",
    enabled: true,
    frequencyMin: 120,
    priority: 2,
    health: "healthy",
    latencyMs: 1800,
    successRate: 91,
    hits24h: 80,
    costPer1k: 0,
    requiresKey: false,
    keySet: true,
    concurrency: 2,
  },
  {
    code: "intelx",
    name: "IntelligenceX",
    category: "darkweb",
    description: "Leaks, pastes, credenciais e brechas.",
    enabled: true,
    frequencyMin: 30,
    priority: 1,
    health: "healthy",
    latencyMs: 640,
    successRate: 97,
    hits24h: 340,
    costPer1k: 12.0,
    requiresKey: true,
    keySet: false,
    concurrency: 3,
    tag: "Premium",
  },
  {
    code: "haveibeenpwned",
    name: "Have I Been Pwned",
    category: "darkweb",
    description: "Vazamentos de e-mails corporativos.",
    enabled: true,
    frequencyMin: 720,
    priority: 2,
    health: "healthy",
    latencyMs: 300,
    successRate: 99.8,
    hits24h: 24,
    costPer1k: 3.5,
    requiresKey: true,
    keySet: false,
    concurrency: 1,
  },
  {
    code: "i2p",
    name: "I2P Search Gateway",
    category: "darkweb",
    description: "Rede I2P para conteúdo hidden.",
    enabled: false,
    frequencyMin: 240,
    priority: 3,
    health: "paused",
    latencyMs: 3200,
    successRate: 76,
    hits24h: 0,
    costPer1k: 0,
    requiresKey: false,
    keySet: true,
    concurrency: 1,
  },
  {
    code: "whoisxml",
    name: "WhoisXML API",
    category: "domain",
    description: "Novos registros, WHOIS histórico e reversos.",
    enabled: true,
    frequencyMin: 30,
    priority: 1,
    health: "healthy",
    latencyMs: 380,
    successRate: 99,
    hits24h: 1420,
    costPer1k: 2.4,
    requiresKey: true,
    keySet: false,
    concurrency: 8,
    tag: "Core",
  },
  {
    code: "certstream",
    name: "CertStream (CT logs)",
    category: "domain",
    description: "Certificados emitidos em tempo real — typosquatting.",
    enabled: true,
    frequencyMin: 1,
    priority: 1,
    health: "healthy",
    latencyMs: 60,
    successRate: 99.9,
    hits24h: 92400,
    costPer1k: 0,
    requiresKey: false,
    keySet: true,
    concurrency: 20,
    tag: "Realtime",
  },
  {
    code: "dnstwist",
    name: "DNSTwist Engine",
    category: "domain",
    description: "Variações permutacionais de domínio.",
    enabled: true,
    frequencyMin: 60,
    priority: 1,
    health: "healthy",
    latencyMs: 900,
    successRate: 98,
    hits24h: 480,
    costPer1k: 0,
    requiresKey: false,
    keySet: true,
    concurrency: 4,
  },
  {
    code: "urlscan",
    name: "urlscan.io",
    category: "domain",
    description: "Screenshots + fingerprint de páginas suspeitas.",
    enabled: true,
    frequencyMin: 15,
    priority: 1,
    health: "healthy",
    latencyMs: 1100,
    successRate: 96.4,
    hits24h: 810,
    costPer1k: 5.0,
    requiresKey: true,
    keySet: false,
    concurrency: 5,
  },
  {
    code: "virustotal",
    name: "VirusTotal",
    category: "domain",
    description: "Reputação de URL, IP e arquivo.",
    enabled: true,
    frequencyMin: 30,
    priority: 2,
    health: "healthy",
    latencyMs: 720,
    successRate: 98.7,
    hits24h: 620,
    costPer1k: 8.0,
    requiresKey: true,
    keySet: false,
    concurrency: 4,
  },
  {
    code: "gnews",
    name: "Google News RSS",
    category: "news",
    description: "Buscas por marca em veículos nacionais.",
    enabled: true,
    frequencyMin: 15,
    priority: 1,
    health: "healthy",
    latencyMs: 340,
    successRate: 99.1,
    hits24h: 780,
    costPer1k: 0,
    requiresKey: false,
    keySet: true,
    concurrency: 6,
  },
  {
    code: "gdelt",
    name: "GDELT Project",
    category: "news",
    description: "Base global de notícias com sentimento.",
    enabled: true,
    frequencyMin: 60,
    priority: 2,
    health: "healthy",
    latencyMs: 620,
    successRate: 97,
    hits24h: 320,
    costPer1k: 0,
    requiresKey: false,
    keySet: true,
    concurrency: 3,
  },
  {
    code: "newsapi",
    name: "NewsAPI.org",
    category: "news",
    description: "Agregador multi-fonte premium.",
    enabled: false,
    frequencyMin: 60,
    priority: 3,
    health: "paused",
    latencyMs: 500,
    successRate: 96,
    hits24h: 0,
    costPer1k: 2.0,
    requiresKey: true,
    keySet: false,
    concurrency: 2,
  },
  {
    code: "reclameaqui",
    name: "Reclame Aqui",
    category: "review",
    description: "Reclamações e reputação empresarial.",
    enabled: true,
    frequencyMin: 30,
    priority: 1,
    health: "healthy",
    latencyMs: 820,
    successRate: 96.3,
    hits24h: 420,
    costPer1k: 0,
    requiresKey: false,
    keySet: true,
    region: "BR",
    concurrency: 4,
    tag: "BR",
  },
  {
    code: "trustpilot",
    name: "Trustpilot",
    category: "review",
    description: "Reviews internacionais e alertas de fraude.",
    enabled: true,
    frequencyMin: 60,
    priority: 2,
    health: "healthy",
    latencyMs: 640,
    successRate: 97,
    hits24h: 210,
    costPer1k: 0,
    requiresKey: true,
    keySet: false,
    concurrency: 3,
  },
  {
    code: "glassdoor",
    name: "Glassdoor Employer",
    category: "review",
    description: "Reputação empregadora e vazamentos internos.",
    enabled: false,
    frequencyMin: 240,
    priority: 3,
    health: "paused",
    latencyMs: 900,
    successRate: 92,
    hits24h: 0,
    costPer1k: 0,
    requiresKey: true,
    keySet: false,
    concurrency: 2,
  },
  {
    code: "youtube",
    name: "YouTube Data API v3",
    category: "video",
    description: "Vídeos, canais, comentários e lives.",
    enabled: true,
    frequencyMin: 10,
    priority: 1,
    health: "healthy",
    latencyMs: 380,
    successRate: 99,
    hits24h: 2140,
    costPer1k: 0,
    requiresKey: true,
    keySet: false,
    concurrency: 8,
    tag: "Core",
  },
  {
    code: "twitch",
    name: "Twitch Helix",
    category: "video",
    description: "Streams e clipes usando a marca.",
    enabled: true,
    frequencyMin: 30,
    priority: 2,
    health: "healthy",
    latencyMs: 420,
    successRate: 98.4,
    hits24h: 320,
    costPer1k: 0,
    requiresKey: true,
    keySet: false,
    concurrency: 3,
  },
  {
    code: "kick",
    name: "Kick.com Public",
    category: "video",
    description: "Streaming alternativo.",
    enabled: false,
    frequencyMin: 120,
    priority: 3,
    health: "paused",
    latencyMs: 700,
    successRate: 90,
    hits24h: 0,
    costPer1k: 0,
    requiresKey: false,
    keySet: true,
    concurrency: 2,
  },
  {
    code: "tg",
    name: "Telegram Public Channels",
    category: "messaging",
    description: "Canais e grupos públicos suspeitos.",
    enabled: true,
    frequencyMin: 15,
    priority: 1,
    health: "healthy",
    latencyMs: 520,
    successRate: 97,
    hits24h: 1120,
    costPer1k: 0,
    requiresKey: true,
    keySet: false,
    concurrency: 5,
    tag: "Sensível",
  },
  {
    code: "discord",
    name: "Discord Public Guilds",
    category: "messaging",
    description: "Servidores abertos indexados.",
    enabled: false,
    frequencyMin: 60,
    priority: 3,
    health: "paused",
    latencyMs: 600,
    successRate: 94,
    hits24h: 0,
    costPer1k: 0,
    requiresKey: true,
    keySet: false,
    concurrency: 2,
  },
  {
    code: "wapub",
    name: "WhatsApp Grupos Públicos",
    category: "messaging",
    description: "Convites indexados na web aberta.",
    enabled: false,
    frequencyMin: 120,
    priority: 3,
    health: "paused",
    latencyMs: 900,
    successRate: 88,
    hits24h: 0,
    costPer1k: 0,
    requiresKey: false,
    keySet: true,
    concurrency: 2,
  },
  {
    code: "chatgpt-index",
    name: "ChatGPT Search Index",
    category: "ai",
    description: "Como sua marca aparece em respostas do ChatGPT.",
    enabled: true,
    frequencyMin: 240,
    priority: 1,
    health: "healthy",
    latencyMs: 1600,
    successRate: 96,
    hits24h: 24,
    costPer1k: 18.0,
    requiresKey: true,
    keySet: false,
    concurrency: 2,
    tag: "GEO",
  },
  {
    code: "perplexity",
    name: "Perplexity Answer Engine",
    category: "ai",
    description: "Menções e citações da marca.",
    enabled: true,
    frequencyMin: 240,
    priority: 2,
    health: "healthy",
    latencyMs: 1400,
    successRate: 95,
    hits24h: 24,
    costPer1k: 12.0,
    requiresKey: true,
    keySet: false,
    concurrency: 2,
  },
  {
    code: "gemini",
    name: "Gemini Web Grounding",
    category: "ai",
    description: "Respostas do Gemini com citação da marca.",
    enabled: true,
    frequencyMin: 240,
    priority: 2,
    health: "healthy",
    latencyMs: 1500,
    successRate: 94,
    hits24h: 24,
    costPer1k: 10.0,
    requiresKey: true,
    keySet: false,
    concurrency: 2,
  },
  {
    code: "claude",
    name: "Claude Web Answers",
    category: "ai",
    description: "Cobertura em conversas com citação web.",
    enabled: false,
    frequencyMin: 240,
    priority: 3,
    health: "paused",
    latencyMs: 1600,
    successRate: 94,
    hits24h: 0,
    costPer1k: 14.0,
    requiresKey: true,
    keySet: false,
    concurrency: 1,
  },
];
