/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardSocialRouteImport } from './routes/dashboard.social'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardReportsRouteImport } from './routes/dashboard.reports'
import { Route as DashboardMonitoringRouteImport } from './routes/dashboard.monitoring'
import { Route as DashboardMarketplaceRouteImport } from './routes/dashboard.marketplace'
import { Route as DashboardLegalRouteImport } from './routes/dashboard.legal'
import { Route as DashboardDomainsRouteImport } from './routes/dashboard.domains'
import { Route as DashboardAlertsRouteImport } from './routes/dashboard.alerts'
import { Route as DashboardAiRouteImport } from './routes/dashboard.ai'
import { Route as DashboardAdsRouteImport } from './routes/dashboard.ads'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSocialRoute = DashboardSocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReportsRoute = DashboardReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMonitoringRoute = DashboardMonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMarketplaceRoute = DashboardMarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLegalRoute = DashboardLegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDomainsRoute = DashboardDomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAlertsRoute = DashboardAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAiRoute = DashboardAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdsRoute = DashboardAdsRouteImport.update({
  id: '/ads',
  path: '/ads',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/ads': typeof DashboardAdsRoute
  '/dashboard/ai': typeof DashboardAiRoute
  '/dashboard/alerts': typeof DashboardAlertsRoute
  '/dashboard/domains': typeof DashboardDomainsRoute
  '/dashboard/legal': typeof DashboardLegalRoute
  '/dashboard/marketplace': typeof DashboardMarketplaceRoute
  '/dashboard/monitoring': typeof DashboardMonitoringRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/social': typeof DashboardSocialRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/ads': typeof DashboardAdsRoute
  '/dashboard/ai': typeof DashboardAiRoute
  '/dashboard/alerts': typeof DashboardAlertsRoute
  '/dashboard/domains': typeof DashboardDomainsRoute
  '/dashboard/legal': typeof DashboardLegalRoute
  '/dashboard/marketplace': typeof DashboardMarketplaceRoute
  '/dashboard/monitoring': typeof DashboardMonitoringRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/social': typeof DashboardSocialRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/ads': typeof DashboardAdsRoute
  '/dashboard/ai': typeof DashboardAiRoute
  '/dashboard/alerts': typeof DashboardAlertsRoute
  '/dashboard/domains': typeof DashboardDomainsRoute
  '/dashboard/legal': typeof DashboardLegalRoute
  '/dashboard/marketplace': typeof DashboardMarketplaceRoute
  '/dashboard/monitoring': typeof DashboardMonitoringRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/social': typeof DashboardSocialRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/ads'
    | '/dashboard/ai'
    | '/dashboard/alerts'
    | '/dashboard/domains'
    | '/dashboard/legal'
    | '/dashboard/marketplace'
    | '/dashboard/monitoring'
    | '/dashboard/reports'
    | '/dashboard/settings'
    | '/dashboard/social'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/ads'
    | '/dashboard/ai'
    | '/dashboard/alerts'
    | '/dashboard/domains'
    | '/dashboard/legal'
    | '/dashboard/marketplace'
    | '/dashboard/monitoring'
    | '/dashboard/reports'
    | '/dashboard/settings'
    | '/dashboard/social'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/ads'
    | '/dashboard/ai'
    | '/dashboard/alerts'
    | '/dashboard/domains'
    | '/dashboard/legal'
    | '/dashboard/marketplace'
    | '/dashboard/monitoring'
    | '/dashboard/reports'
    | '/dashboard/settings'
    | '/dashboard/social'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/social': {
      id: '/dashboard/social'
      path: '/social'
      fullPath: '/dashboard/social'
      preLoaderRoute: typeof DashboardSocialRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reports': {
      id: '/dashboard/reports'
      path: '/reports'
      fullPath: '/dashboard/reports'
      preLoaderRoute: typeof DashboardReportsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/monitoring': {
      id: '/dashboard/monitoring'
      path: '/monitoring'
      fullPath: '/dashboard/monitoring'
      preLoaderRoute: typeof DashboardMonitoringRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/marketplace': {
      id: '/dashboard/marketplace'
      path: '/marketplace'
      fullPath: '/dashboard/marketplace'
      preLoaderRoute: typeof DashboardMarketplaceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/legal': {
      id: '/dashboard/legal'
      path: '/legal'
      fullPath: '/dashboard/legal'
      preLoaderRoute: typeof DashboardLegalRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/domains': {
      id: '/dashboard/domains'
      path: '/domains'
      fullPath: '/dashboard/domains'
      preLoaderRoute: typeof DashboardDomainsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/alerts': {
      id: '/dashboard/alerts'
      path: '/alerts'
      fullPath: '/dashboard/alerts'
      preLoaderRoute: typeof DashboardAlertsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ai': {
      id: '/dashboard/ai'
      path: '/ai'
      fullPath: '/dashboard/ai'
      preLoaderRoute: typeof DashboardAiRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ads': {
      id: '/dashboard/ads'
      path: '/ads'
      fullPath: '/dashboard/ads'
      preLoaderRoute: typeof DashboardAdsRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAdsRoute: typeof DashboardAdsRoute
  DashboardAiRoute: typeof DashboardAiRoute
  DashboardAlertsRoute: typeof DashboardAlertsRoute
  DashboardDomainsRoute: typeof DashboardDomainsRoute
  DashboardLegalRoute: typeof DashboardLegalRoute
  DashboardMarketplaceRoute: typeof DashboardMarketplaceRoute
  DashboardMonitoringRoute: typeof DashboardMonitoringRoute
  DashboardReportsRoute: typeof DashboardReportsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardSocialRoute: typeof DashboardSocialRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAdsRoute: DashboardAdsRoute,
  DashboardAiRoute: DashboardAiRoute,
  DashboardAlertsRoute: DashboardAlertsRoute,
  DashboardDomainsRoute: DashboardDomainsRoute,
  DashboardLegalRoute: DashboardLegalRoute,
  DashboardMarketplaceRoute: DashboardMarketplaceRoute,
  DashboardMonitoringRoute: DashboardMonitoringRoute,
  DashboardReportsRoute: DashboardReportsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardSocialRoute: DashboardSocialRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
