/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreNosRouteImport } from './routes/sobre-nos'
import { Route as Register2RouteImport } from './routes/register2'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PropostaRouteImport } from './routes/proposta'
import { Route as Login2RouteImport } from './routes/login2'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JuridicoRouteImport } from './routes/juridico'
import { Route as DiferencialRouteImport } from './routes/diferencial'
import { Route as DiagnosticoRouteImport } from './routes/diagnostico'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ComoFuncionaRouteImport } from './routes/como-funciona'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardWarroomRouteImport } from './routes/dashboard.warroom'
import { Route as DashboardThreatsRouteImport } from './routes/dashboard.threats'
import { Route as DashboardSocialRouteImport } from './routes/dashboard.social'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardRoiRouteImport } from './routes/dashboard.roi'
import { Route as DashboardReportsRouteImport } from './routes/dashboard.reports'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardPredictRouteImport } from './routes/dashboard.predict'
import { Route as DashboardPlaybooksRouteImport } from './routes/dashboard.playbooks'
import { Route as DashboardPagamentoRouteImport } from './routes/dashboard.pagamento'
import { Route as DashboardOnboardingRouteImport } from './routes/dashboard.onboarding'
import { Route as DashboardMonitoringRouteImport } from './routes/dashboard.monitoring'
import { Route as DashboardMarketplaceRouteImport } from './routes/dashboard.marketplace'
import { Route as DashboardLegalRouteImport } from './routes/dashboard.legal'
import { Route as DashboardInfluencersRouteImport } from './routes/dashboard.influencers'
import { Route as DashboardDomainsRouteImport } from './routes/dashboard.domains'
import { Route as DashboardDeepfakeRouteImport } from './routes/dashboard.deepfake'
import { Route as DashboardDarkwebRouteImport } from './routes/dashboard.darkweb'
import { Route as DashboardCrisisRouteImport } from './routes/dashboard.crisis'
import { Route as DashboardCompetitorsRouteImport } from './routes/dashboard.competitors'
import { Route as DashboardBriefingRouteImport } from './routes/dashboard.briefing'
import { Route as DashboardAutopilotRouteImport } from './routes/dashboard.autopilot'
import { Route as DashboardAppsRouteImport } from './routes/dashboard.apps'
import { Route as DashboardAlertsRouteImport } from './routes/dashboard.alerts'
import { Route as DashboardAiRouteImport } from './routes/dashboard.ai'
import { Route as DashboardAdsRouteImport } from './routes/dashboard.ads'

const SobreNosRoute = SobreNosRouteImport.update({
  id: '/sobre-nos',
  path: '/sobre-nos',
  getParentRoute: () => rootRouteImport,
} as any)
const Register2Route = Register2RouteImport.update({
  id: '/register2',
  path: '/register2',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PropostaRoute = PropostaRouteImport.update({
  id: '/proposta',
  path: '/proposta',
  getParentRoute: () => rootRouteImport,
} as any)
const Login2Route = Login2RouteImport.update({
  id: '/login2',
  path: '/login2',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JuridicoRoute = JuridicoRouteImport.update({
  id: '/juridico',
  path: '/juridico',
  getParentRoute: () => rootRouteImport,
} as any)
const DiferencialRoute = DiferencialRouteImport.update({
  id: '/diferencial',
  path: '/diferencial',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticoRoute = DiagnosticoRouteImport.update({
  id: '/diagnostico',
  path: '/diagnostico',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoFuncionaRoute = ComoFuncionaRouteImport.update({
  id: '/como-funciona',
  path: '/como-funciona',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWarroomRoute = DashboardWarroomRouteImport.update({
  id: '/warroom',
  path: '/warroom',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardThreatsRoute = DashboardThreatsRouteImport.update({
  id: '/threats',
  path: '/threats',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSocialRoute = DashboardSocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRoiRoute = DashboardRoiRouteImport.update({
  id: '/roi',
  path: '/roi',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReportsRoute = DashboardReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPredictRoute = DashboardPredictRouteImport.update({
  id: '/predict',
  path: '/predict',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPlaybooksRoute = DashboardPlaybooksRouteImport.update({
  id: '/playbooks',
  path: '/playbooks',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPagamentoRoute = DashboardPagamentoRouteImport.update({
  id: '/pagamento',
  path: '/pagamento',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOnboardingRoute = DashboardOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMonitoringRoute = DashboardMonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMarketplaceRoute = DashboardMarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLegalRoute = DashboardLegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInfluencersRoute = DashboardInfluencersRouteImport.update({
  id: '/influencers',
  path: '/influencers',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDomainsRoute = DashboardDomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDeepfakeRoute = DashboardDeepfakeRouteImport.update({
  id: '/deepfake',
  path: '/deepfake',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDarkwebRoute = DashboardDarkwebRouteImport.update({
  id: '/darkweb',
  path: '/darkweb',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCrisisRoute = DashboardCrisisRouteImport.update({
  id: '/crisis',
  path: '/crisis',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCompetitorsRoute = DashboardCompetitorsRouteImport.update({
  id: '/competitors',
  path: '/competitors',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBriefingRoute = DashboardBriefingRouteImport.update({
  id: '/briefing',
  path: '/briefing',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAutopilotRoute = DashboardAutopilotRouteImport.update({
  id: '/autopilot',
  path: '/autopilot',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAppsRoute = DashboardAppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAlertsRoute = DashboardAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAiRoute = DashboardAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdsRoute = DashboardAdsRouteImport.update({
  id: '/ads',
  path: '/ads',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/diagnostico': typeof DiagnosticoRoute
  '/diferencial': typeof DiferencialRoute
  '/juridico': typeof JuridicoRoute
  '/login': typeof LoginRoute
  '/login2': typeof Login2Route
  '/proposta': typeof PropostaRoute
  '/register': typeof RegisterRoute
  '/register2': typeof Register2Route
  '/sobre-nos': typeof SobreNosRoute
  '/dashboard/ads': typeof DashboardAdsRoute
  '/dashboard/ai': typeof DashboardAiRoute
  '/dashboard/alerts': typeof DashboardAlertsRoute
  '/dashboard/apps': typeof DashboardAppsRoute
  '/dashboard/autopilot': typeof DashboardAutopilotRoute
  '/dashboard/briefing': typeof DashboardBriefingRoute
  '/dashboard/competitors': typeof DashboardCompetitorsRoute
  '/dashboard/crisis': typeof DashboardCrisisRoute
  '/dashboard/darkweb': typeof DashboardDarkwebRoute
  '/dashboard/deepfake': typeof DashboardDeepfakeRoute
  '/dashboard/domains': typeof DashboardDomainsRoute
  '/dashboard/influencers': typeof DashboardInfluencersRoute
  '/dashboard/legal': typeof DashboardLegalRoute
  '/dashboard/marketplace': typeof DashboardMarketplaceRoute
  '/dashboard/monitoring': typeof DashboardMonitoringRoute
  '/dashboard/onboarding': typeof DashboardOnboardingRoute
  '/dashboard/pagamento': typeof DashboardPagamentoRoute
  '/dashboard/playbooks': typeof DashboardPlaybooksRoute
  '/dashboard/predict': typeof DashboardPredictRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/roi': typeof DashboardRoiRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/social': typeof DashboardSocialRoute
  '/dashboard/threats': typeof DashboardThreatsRoute
  '/dashboard/warroom': typeof DashboardWarroomRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/diferencial': typeof DiferencialRoute
  '/juridico': typeof JuridicoRoute
  '/login': typeof LoginRoute
  '/login2': typeof Login2Route
  '/proposta': typeof PropostaRoute
  '/register': typeof RegisterRoute
  '/register2': typeof Register2Route
  '/sobre-nos': typeof SobreNosRoute
  '/dashboard/ads': typeof DashboardAdsRoute
  '/dashboard/ai': typeof DashboardAiRoute
  '/dashboard/alerts': typeof DashboardAlertsRoute
  '/dashboard/apps': typeof DashboardAppsRoute
  '/dashboard/autopilot': typeof DashboardAutopilotRoute
  '/dashboard/briefing': typeof DashboardBriefingRoute
  '/dashboard/competitors': typeof DashboardCompetitorsRoute
  '/dashboard/crisis': typeof DashboardCrisisRoute
  '/dashboard/darkweb': typeof DashboardDarkwebRoute
  '/dashboard/deepfake': typeof DashboardDeepfakeRoute
  '/dashboard/domains': typeof DashboardDomainsRoute
  '/dashboard/influencers': typeof DashboardInfluencersRoute
  '/dashboard/legal': typeof DashboardLegalRoute
  '/dashboard/marketplace': typeof DashboardMarketplaceRoute
  '/dashboard/monitoring': typeof DashboardMonitoringRoute
  '/dashboard/onboarding': typeof DashboardOnboardingRoute
  '/dashboard/pagamento': typeof DashboardPagamentoRoute
  '/dashboard/playbooks': typeof DashboardPlaybooksRoute
  '/dashboard/predict': typeof DashboardPredictRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/roi': typeof DashboardRoiRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/social': typeof DashboardSocialRoute
  '/dashboard/threats': typeof DashboardThreatsRoute
  '/dashboard/warroom': typeof DashboardWarroomRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/diagnostico': typeof DiagnosticoRoute
  '/diferencial': typeof DiferencialRoute
  '/juridico': typeof JuridicoRoute
  '/login': typeof LoginRoute
  '/login2': typeof Login2Route
  '/proposta': typeof PropostaRoute
  '/register': typeof RegisterRoute
  '/register2': typeof Register2Route
  '/sobre-nos': typeof SobreNosRoute
  '/dashboard/ads': typeof DashboardAdsRoute
  '/dashboard/ai': typeof DashboardAiRoute
  '/dashboard/alerts': typeof DashboardAlertsRoute
  '/dashboard/apps': typeof DashboardAppsRoute
  '/dashboard/autopilot': typeof DashboardAutopilotRoute
  '/dashboard/briefing': typeof DashboardBriefingRoute
  '/dashboard/competitors': typeof DashboardCompetitorsRoute
  '/dashboard/crisis': typeof DashboardCrisisRoute
  '/dashboard/darkweb': typeof DashboardDarkwebRoute
  '/dashboard/deepfake': typeof DashboardDeepfakeRoute
  '/dashboard/domains': typeof DashboardDomainsRoute
  '/dashboard/influencers': typeof DashboardInfluencersRoute
  '/dashboard/legal': typeof DashboardLegalRoute
  '/dashboard/marketplace': typeof DashboardMarketplaceRoute
  '/dashboard/monitoring': typeof DashboardMonitoringRoute
  '/dashboard/onboarding': typeof DashboardOnboardingRoute
  '/dashboard/pagamento': typeof DashboardPagamentoRoute
  '/dashboard/playbooks': typeof DashboardPlaybooksRoute
  '/dashboard/predict': typeof DashboardPredictRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/roi': typeof DashboardRoiRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/social': typeof DashboardSocialRoute
  '/dashboard/threats': typeof DashboardThreatsRoute
  '/dashboard/warroom': typeof DashboardWarroomRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/como-funciona'
    | '/dashboard'
    | '/diagnostico'
    | '/diferencial'
    | '/juridico'
    | '/login'
    | '/login2'
    | '/proposta'
    | '/register'
    | '/register2'
    | '/sobre-nos'
    | '/dashboard/ads'
    | '/dashboard/ai'
    | '/dashboard/alerts'
    | '/dashboard/apps'
    | '/dashboard/autopilot'
    | '/dashboard/briefing'
    | '/dashboard/competitors'
    | '/dashboard/crisis'
    | '/dashboard/darkweb'
    | '/dashboard/deepfake'
    | '/dashboard/domains'
    | '/dashboard/influencers'
    | '/dashboard/legal'
    | '/dashboard/marketplace'
    | '/dashboard/monitoring'
    | '/dashboard/onboarding'
    | '/dashboard/pagamento'
    | '/dashboard/playbooks'
    | '/dashboard/predict'
    | '/dashboard/profile'
    | '/dashboard/reports'
    | '/dashboard/roi'
    | '/dashboard/settings'
    | '/dashboard/social'
    | '/dashboard/threats'
    | '/dashboard/warroom'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/como-funciona'
    | '/diagnostico'
    | '/diferencial'
    | '/juridico'
    | '/login'
    | '/login2'
    | '/proposta'
    | '/register'
    | '/register2'
    | '/sobre-nos'
    | '/dashboard/ads'
    | '/dashboard/ai'
    | '/dashboard/alerts'
    | '/dashboard/apps'
    | '/dashboard/autopilot'
    | '/dashboard/briefing'
    | '/dashboard/competitors'
    | '/dashboard/crisis'
    | '/dashboard/darkweb'
    | '/dashboard/deepfake'
    | '/dashboard/domains'
    | '/dashboard/influencers'
    | '/dashboard/legal'
    | '/dashboard/marketplace'
    | '/dashboard/monitoring'
    | '/dashboard/onboarding'
    | '/dashboard/pagamento'
    | '/dashboard/playbooks'
    | '/dashboard/predict'
    | '/dashboard/profile'
    | '/dashboard/reports'
    | '/dashboard/roi'
    | '/dashboard/settings'
    | '/dashboard/social'
    | '/dashboard/threats'
    | '/dashboard/warroom'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/como-funciona'
    | '/dashboard'
    | '/diagnostico'
    | '/diferencial'
    | '/juridico'
    | '/login'
    | '/login2'
    | '/proposta'
    | '/register'
    | '/register2'
    | '/sobre-nos'
    | '/dashboard/ads'
    | '/dashboard/ai'
    | '/dashboard/alerts'
    | '/dashboard/apps'
    | '/dashboard/autopilot'
    | '/dashboard/briefing'
    | '/dashboard/competitors'
    | '/dashboard/crisis'
    | '/dashboard/darkweb'
    | '/dashboard/deepfake'
    | '/dashboard/domains'
    | '/dashboard/influencers'
    | '/dashboard/legal'
    | '/dashboard/marketplace'
    | '/dashboard/monitoring'
    | '/dashboard/onboarding'
    | '/dashboard/pagamento'
    | '/dashboard/playbooks'
    | '/dashboard/predict'
    | '/dashboard/profile'
    | '/dashboard/reports'
    | '/dashboard/roi'
    | '/dashboard/settings'
    | '/dashboard/social'
    | '/dashboard/threats'
    | '/dashboard/warroom'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComoFuncionaRoute: typeof ComoFuncionaRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DiagnosticoRoute: typeof DiagnosticoRoute
  DiferencialRoute: typeof DiferencialRoute
  JuridicoRoute: typeof JuridicoRoute
  LoginRoute: typeof LoginRoute
  Login2Route: typeof Login2Route
  PropostaRoute: typeof PropostaRoute
  RegisterRoute: typeof RegisterRoute
  Register2Route: typeof Register2Route
  SobreNosRoute: typeof SobreNosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre-nos': {
      id: '/sobre-nos'
      path: '/sobre-nos'
      fullPath: '/sobre-nos'
      preLoaderRoute: typeof SobreNosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register2': {
      id: '/register2'
      path: '/register2'
      fullPath: '/register2'
      preLoaderRoute: typeof Register2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proposta': {
      id: '/proposta'
      path: '/proposta'
      fullPath: '/proposta'
      preLoaderRoute: typeof PropostaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login2': {
      id: '/login2'
      path: '/login2'
      fullPath: '/login2'
      preLoaderRoute: typeof Login2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/juridico': {
      id: '/juridico'
      path: '/juridico'
      fullPath: '/juridico'
      preLoaderRoute: typeof JuridicoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diferencial': {
      id: '/diferencial'
      path: '/diferencial'
      fullPath: '/diferencial'
      preLoaderRoute: typeof DiferencialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostico': {
      id: '/diagnostico'
      path: '/diagnostico'
      fullPath: '/diagnostico'
      preLoaderRoute: typeof DiagnosticoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-funciona': {
      id: '/como-funciona'
      path: '/como-funciona'
      fullPath: '/como-funciona'
      preLoaderRoute: typeof ComoFuncionaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/warroom': {
      id: '/dashboard/warroom'
      path: '/warroom'
      fullPath: '/dashboard/warroom'
      preLoaderRoute: typeof DashboardWarroomRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/threats': {
      id: '/dashboard/threats'
      path: '/threats'
      fullPath: '/dashboard/threats'
      preLoaderRoute: typeof DashboardThreatsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/social': {
      id: '/dashboard/social'
      path: '/social'
      fullPath: '/dashboard/social'
      preLoaderRoute: typeof DashboardSocialRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/roi': {
      id: '/dashboard/roi'
      path: '/roi'
      fullPath: '/dashboard/roi'
      preLoaderRoute: typeof DashboardRoiRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reports': {
      id: '/dashboard/reports'
      path: '/reports'
      fullPath: '/dashboard/reports'
      preLoaderRoute: typeof DashboardReportsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/predict': {
      id: '/dashboard/predict'
      path: '/predict'
      fullPath: '/dashboard/predict'
      preLoaderRoute: typeof DashboardPredictRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/playbooks': {
      id: '/dashboard/playbooks'
      path: '/playbooks'
      fullPath: '/dashboard/playbooks'
      preLoaderRoute: typeof DashboardPlaybooksRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/pagamento': {
      id: '/dashboard/pagamento'
      path: '/pagamento'
      fullPath: '/dashboard/pagamento'
      preLoaderRoute: typeof DashboardPagamentoRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/onboarding': {
      id: '/dashboard/onboarding'
      path: '/onboarding'
      fullPath: '/dashboard/onboarding'
      preLoaderRoute: typeof DashboardOnboardingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/monitoring': {
      id: '/dashboard/monitoring'
      path: '/monitoring'
      fullPath: '/dashboard/monitoring'
      preLoaderRoute: typeof DashboardMonitoringRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/marketplace': {
      id: '/dashboard/marketplace'
      path: '/marketplace'
      fullPath: '/dashboard/marketplace'
      preLoaderRoute: typeof DashboardMarketplaceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/legal': {
      id: '/dashboard/legal'
      path: '/legal'
      fullPath: '/dashboard/legal'
      preLoaderRoute: typeof DashboardLegalRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/influencers': {
      id: '/dashboard/influencers'
      path: '/influencers'
      fullPath: '/dashboard/influencers'
      preLoaderRoute: typeof DashboardInfluencersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/domains': {
      id: '/dashboard/domains'
      path: '/domains'
      fullPath: '/dashboard/domains'
      preLoaderRoute: typeof DashboardDomainsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/deepfake': {
      id: '/dashboard/deepfake'
      path: '/deepfake'
      fullPath: '/dashboard/deepfake'
      preLoaderRoute: typeof DashboardDeepfakeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/darkweb': {
      id: '/dashboard/darkweb'
      path: '/darkweb'
      fullPath: '/dashboard/darkweb'
      preLoaderRoute: typeof DashboardDarkwebRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/crisis': {
      id: '/dashboard/crisis'
      path: '/crisis'
      fullPath: '/dashboard/crisis'
      preLoaderRoute: typeof DashboardCrisisRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/competitors': {
      id: '/dashboard/competitors'
      path: '/competitors'
      fullPath: '/dashboard/competitors'
      preLoaderRoute: typeof DashboardCompetitorsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/briefing': {
      id: '/dashboard/briefing'
      path: '/briefing'
      fullPath: '/dashboard/briefing'
      preLoaderRoute: typeof DashboardBriefingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/autopilot': {
      id: '/dashboard/autopilot'
      path: '/autopilot'
      fullPath: '/dashboard/autopilot'
      preLoaderRoute: typeof DashboardAutopilotRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/apps': {
      id: '/dashboard/apps'
      path: '/apps'
      fullPath: '/dashboard/apps'
      preLoaderRoute: typeof DashboardAppsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/alerts': {
      id: '/dashboard/alerts'
      path: '/alerts'
      fullPath: '/dashboard/alerts'
      preLoaderRoute: typeof DashboardAlertsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ai': {
      id: '/dashboard/ai'
      path: '/ai'
      fullPath: '/dashboard/ai'
      preLoaderRoute: typeof DashboardAiRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ads': {
      id: '/dashboard/ads'
      path: '/ads'
      fullPath: '/dashboard/ads'
      preLoaderRoute: typeof DashboardAdsRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAdsRoute: typeof DashboardAdsRoute
  DashboardAiRoute: typeof DashboardAiRoute
  DashboardAlertsRoute: typeof DashboardAlertsRoute
  DashboardAppsRoute: typeof DashboardAppsRoute
  DashboardAutopilotRoute: typeof DashboardAutopilotRoute
  DashboardBriefingRoute: typeof DashboardBriefingRoute
  DashboardCompetitorsRoute: typeof DashboardCompetitorsRoute
  DashboardCrisisRoute: typeof DashboardCrisisRoute
  DashboardDarkwebRoute: typeof DashboardDarkwebRoute
  DashboardDeepfakeRoute: typeof DashboardDeepfakeRoute
  DashboardDomainsRoute: typeof DashboardDomainsRoute
  DashboardInfluencersRoute: typeof DashboardInfluencersRoute
  DashboardLegalRoute: typeof DashboardLegalRoute
  DashboardMarketplaceRoute: typeof DashboardMarketplaceRoute
  DashboardMonitoringRoute: typeof DashboardMonitoringRoute
  DashboardOnboardingRoute: typeof DashboardOnboardingRoute
  DashboardPagamentoRoute: typeof DashboardPagamentoRoute
  DashboardPlaybooksRoute: typeof DashboardPlaybooksRoute
  DashboardPredictRoute: typeof DashboardPredictRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardReportsRoute: typeof DashboardReportsRoute
  DashboardRoiRoute: typeof DashboardRoiRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardSocialRoute: typeof DashboardSocialRoute
  DashboardThreatsRoute: typeof DashboardThreatsRoute
  DashboardWarroomRoute: typeof DashboardWarroomRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAdsRoute: DashboardAdsRoute,
  DashboardAiRoute: DashboardAiRoute,
  DashboardAlertsRoute: DashboardAlertsRoute,
  DashboardAppsRoute: DashboardAppsRoute,
  DashboardAutopilotRoute: DashboardAutopilotRoute,
  DashboardBriefingRoute: DashboardBriefingRoute,
  DashboardCompetitorsRoute: DashboardCompetitorsRoute,
  DashboardCrisisRoute: DashboardCrisisRoute,
  DashboardDarkwebRoute: DashboardDarkwebRoute,
  DashboardDeepfakeRoute: DashboardDeepfakeRoute,
  DashboardDomainsRoute: DashboardDomainsRoute,
  DashboardInfluencersRoute: DashboardInfluencersRoute,
  DashboardLegalRoute: DashboardLegalRoute,
  DashboardMarketplaceRoute: DashboardMarketplaceRoute,
  DashboardMonitoringRoute: DashboardMonitoringRoute,
  DashboardOnboardingRoute: DashboardOnboardingRoute,
  DashboardPagamentoRoute: DashboardPagamentoRoute,
  DashboardPlaybooksRoute: DashboardPlaybooksRoute,
  DashboardPredictRoute: DashboardPredictRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardReportsRoute: DashboardReportsRoute,
  DashboardRoiRoute: DashboardRoiRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardSocialRoute: DashboardSocialRoute,
  DashboardThreatsRoute: DashboardThreatsRoute,
  DashboardWarroomRoute: DashboardWarroomRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComoFuncionaRoute: ComoFuncionaRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DiagnosticoRoute: DiagnosticoRoute,
  DiferencialRoute: DiferencialRoute,
  JuridicoRoute: JuridicoRoute,
  LoginRoute: LoginRoute,
  Login2Route: Login2Route,
  PropostaRoute: PropostaRoute,
  RegisterRoute: RegisterRoute,
  Register2Route: Register2Route,
  SobreNosRoute: SobreNosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
